name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.11.3"  # Latest version
      
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: "0.39.0"  # Latest stable version
      
      - name: Check Versions
        run: |
          scarb --version
          snforge -V
      
      - name: Format Check
        run: scarb fmt --check
      
      - name: Run Tests
        run: snforge test
      
      - name: Build Project
        run: scarb build
